package project.demo.model;

public enum Sector {
    AGRICULTURE_HORTICULTURE,
    BUSINESS_SERVICES,
    CONSTRUCTION,
    CULTURE_SPORTS_RECREATION,
    ENERGY_WATER_ENVIRONMENT,
    FINANCE,
    HEALTHCARE,
    HOSPITALITY,
    ICT_AND_MEDIA,
    INDUSTRIAL,
    LOGISTICS,
    OTHER,
    RETAIL,
    WHOLESALE
}
